version: '3'

services:
  wordpos-svc:
    image: dushyant03/nodejs
    environment:
      - BASE_PATH=lyrics-svc:8080
    ports:
     - "80:3000"
    links:
      - lyrics-svc:lyrics-svc

  lyrics-svc:
    image: dushyant03/lyrics.ovh
    expose:
      - "8080" 
      - "8081"
